name: Build ZMK firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ZMK for Nice Nano V2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Mostrar estrutura de diret√≥rios
        run: ls -R $GITHUB_WORKSPACE

      - name: Setup Zephyr environment
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          toolchains: arm-zephyr-eabi

      - name: Initialize project
        run: |
          cd $GITHUB_WORKSPACE
          west init -l $GITHUB_WORKSPACE/config
          west update

      - name: Build firmware
        run: west build -s ./zmk/app -d build/left -- -DSHIELD=nice_nano_v2
